development:
  firstname: revathi
  lastname: parimi
  password: revathi
  emailid: revathi.parimi@gmail.com
  phonenumber: 7032427643
  gender: female
  qualification: softwareengineer
  language: english
  address: vizag